# Generated by Django 3.1.5 on 2021-01-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0002_blogform_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogform',
            name='blog_title',
        ),
    ]
