# Generated by Django 3.1.5 on 2021-01-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0003_remove_blogform_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogform',
            name='blogId',
            field=models.IntegerField(default=1, max_length=100000000, verbose_name='بلاگ'),
        ),
    ]
