# Generated by Django 3.1.5 on 2021-01-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0004_blogform_blogid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogform',
            name='blogId',
            field=models.IntegerField(default=1, verbose_name='بلاگ'),
        ),
    ]
