# Generated by Django 3.1.5 on 2021-01-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'پنل کاربران',
            },
        ),
    ]
