# Generated by Django 3.1.5 on 2021-01-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpanel',
            name='full_name',
        ),
        migrations.AddField(
            model_name='userpanel',
            name='first_name',
            field=models.CharField(default='', max_length=150, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='userpanel',
            name='last_name',
            field=models.CharField(default='', max_length=150, verbose_name=' نام خانوادگی'),
        ),
    ]
