# Generated by Django 3.1.5 on 2021-01-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_account', '0002_auto_20210127_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpanel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='تصویر'),
        ),
    ]
