# Generated by Django 3.1.5 on 2021-01-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_account', '0004_auto_20210127_1923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPanel',
        ),
    ]
