# Generated by Django 3.1.5 on 2021-01-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سایت')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='شماره تماس')),
                ('fax', models.CharField(blank=True, max_length=30, null=True, verbose_name='فکس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('map', models.ImageField(blank=True, null=True, upload_to='map', verbose_name='نقشه')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='لوگوی سایت(48*48)')),
                ('description', models.TextField(verbose_name='توضیحات درباره سایت')),
            ],
            options={
                'verbose_name': 'تنظیم سایت',
                'verbose_name_plural': 'تنظیم اطلاعات سایت',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=200, verbose_name='روز')),
                ('times', models.CharField(default='16:00 - 8:00 یا تعطیل', max_length=300, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعات کاری',
            },
        ),
    ]
