# Generated by Django 3.1.5 on 2021-01-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='copy_right',
            field=models.CharField(default=' ', max_length=200, verbose_name='متن کپی رایت'),
        ),
    ]
