# Generated by Django 3.1.5 on 2021-01-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.ImageField(upload_to='', verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=200, verbose_name='عنوان پیام')),
                ('text', models.TextField(verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس های کاربران ',
            },
        ),
    ]
