# Generated by Django 3.1.5 on 2021-01-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('product_size', models.CharField(max_length=500, verbose_name='سایز محصول')),
                ('color', models.CharField(choices=[('r', 'قرمز'), ('y', 'زرد'), ('b', 'آبی'), ('b', 'سیاه')], default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='تصویر محصول')),
                ('brand', models.CharField(max_length=200, verbose_name='برند')),
                ('active', models.BooleanField(default=False, verbose_name='موجود / ناموجود')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
