# Generated by Django 3.1.5 on 2021-01-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='قیمت'),
        ),
    ]
