# Generated by Django 3.1.5 on 2021-01-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('r', 'قرمز'), ('y', 'زرد'), ('b', 'آبی'), ('b', 'سیاه'), ('w', 'سفید')], default='r', max_length=200),
        ),
    ]
