# Generated by Django 3.1.5 on 2021-01-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0003_auto_20210122_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_type',
            field=models.CharField(choices=[('n', 'جدید'), ('null', 'Null')], default='null', max_length=200),
        ),
    ]
