# Generated by Django 3.1.5 on 2021-01-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0015_product_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special',
            field=models.BooleanField(default=False, verbose_name='محصول ویژه'),
        ),
    ]
