# Generated by Django 3.1.5 on 2021-01-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0017_auto_20210123_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_type',
            field=models.CharField(choices=[('جدید', 'بله'), (' ', 'خیر')], default='no', max_length=200, verbose_name='جدید'),
        ),
    ]
