# Generated by Django 3.1.5 on 2021-01-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0018_auto_20210123_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='متن نظر')),
            ],
            options={
                'verbose_name': 'نظر کاربران',
                'verbose_name_plural': 'نطرات کاربران درباره محصول',
            },
        ),
    ]
