# Generated by Django 3.1.5 on 2021-01-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0019_productform'),
    ]

    operations = [
        migrations.AddField(
            model_name='productform',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده / نشده'),
        ),
    ]
