# Generated by Django 3.1.5 on 2021-01-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0020_productform_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productform',
            options={'verbose_name': 'نظر کاربران', 'verbose_name_plural': 'نطرات کاربران درباره محصولات'},
        ),
    ]
