# Generated by Django 3.1.5 on 2021-01-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0026_auto_20210125_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default='1000', null=True, verbose_name='قیمت'),
        ),
    ]
