# Generated by Django 3.1.5 on 2021-01-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0028_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Gallery', verbose_name='تصویر اول'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Gallery', verbose_name='تصویر دوم'),
        ),
    ]
