# Generated by Django 3.1.5 on 2021-01-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0029_auto_20210128_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='product',
        ),
        migrations.AddField(
            model_name='productgallery',
            name='product',
            field=models.ManyToManyField(to='shop_products.Product', verbose_name='محصول'),
        ),
    ]
