# Generated by Django 3.1.5 on 2021-01-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0031_auto_20210128_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='productform',
            name='productId',
            field=models.IntegerField(default=1, verbose_name='محصول'),
        ),
    ]
