# Generated by Django 3.1.5 on 2021-01-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0002_auto_20210125_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.CharField(max_length=200, verbose_name='قیمت'),
        ),
    ]
