# Generated by Django 3.1.5 on 2021-01-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0003_auto_20210125_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.FloatField(verbose_name='قیمت'),
        ),
    ]
