# Generated by Django 3.1.5 on 2021-01-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0006_auto_20210125_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='نام ونام خانوادگی')),
                ('phone', models.CharField(max_length=15, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.CharField(max_length=1000, verbose_name='آدرس')),
                ('city', models.CharField(max_length=500, verbose_name='شهر')),
                ('postal_code', models.CharField(max_length=25, verbose_name='کد پستی')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست ها',
            },
        ),
    ]
